# Generated by Django 2.2.14 on 2020-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category_id',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_id',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
