# Generated by Django 2.2.14 on 2020-07-22 08:37

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200722_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=mapbox_location_field.models.LocationField(default=None, map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
