# Generated by Django 2.2.14 on 2020-07-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
