# Generated by Django 2.2.14 on 2020-07-22 10:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_unique_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_status',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='os_type',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
