# Generated by Django 2.2.14 on 2020-07-23 16:44

import dashboard.forms
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_uid', models.PositiveIntegerField()),
                ('event_description', models.TextField()),
                ('event_scheduled_status', models.PositiveIntegerField()),
                ('event_venue', models.CharField(max_length=255, unique=True)),
                ('event_agenda', dashboard.forms.CustomListField(blank=True, default={}, null=True)),
                ('event_start_date', models.FloatField(blank=True)),
                ('event_end_date', models.FloatField(blank=True)),
                ('event_location', dashboard.forms.CustomDictField(blank=True, default={}, null=True)),
                ('event_points', models.PositiveIntegerField()),
                ('event_maximum_attende', models.PositiveIntegerField()),
                ('updated_date', models.FloatField(default=1595522649)),
                ('created_date', models.FloatField(default=1595522649)),
                ('status', models.PositiveIntegerField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [17.031645, 51.106715], 'cursor_style': 'pointer', 'marker_color': 'blue', 'zoom': 2})),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1000)),
                ('image_position', models.PositiveIntegerField()),
                ('created_date', models.FloatField(default=1595522649)),
                ('updated_date', models.FloatField(default=1595522649)),
                ('status', models.PositiveIntegerField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_event_image', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image_event', to='event.Event')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user_event_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_code', models.CharField(max_length=255, unique=True)),
                ('category_image_url', models.CharField(max_length=1000)),
                ('category_priority', models.PositiveIntegerField(unique=True)),
                ('created_date', models.FloatField(default=1595522649)),
                ('updated_date', models.FloatField(default=1595522649)),
                ('status', models.PositiveIntegerField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EventCategories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_category_name', to='event.EventCategories'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
