# Generated by Django 2.2.14 on 2020-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategories',
            name='category_image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
