# Generated by Django 2.2.14 on 2020-07-22 07:51

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200722_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'})),
            ],
        ),
    ]
