# Generated by Django 2.2.14 on 2020-07-22 09:06

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(default=None, map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
