# Generated by Django 2.2.14 on 2020-07-22 09:58

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200722_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [28.6139, 77.209], 'cursor_style': 'pointer', 'marker_color': 'blue', 'zoom': 2}),
        ),
    ]
