# Generated by Django 2.2.14 on 2020-07-22 10:01

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200722_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [17.031645, 51.106715], 'cursor_style': 'pointer', 'marker_color': 'blue', 'zoom': 2}),
        ),
    ]
